### ISSUE TITLE
Parsing problem for an embeded function

### ISSUE THREAD

**Issue by gordonwatts** [iris-hep/func_adl#136]
```
    query = ds.Select(
        lambda e: {
            "evt": e.EventInfo("EventInfo"),
            "jet": e.Jets("AnalysisJets", calibrate=False),
        }
    ).Select(
        lambda ei: {
            "event_number": ei.evt.eventNumber(),
            "run_number": ei.evt.runNumber(),
            "jet_pt": ei.jet.Select(lambda j: j.pt() / 1000),
        }
    )
```

Causes this crash:

```
PS C:\Users\gordo\Code\iris-hep\idap-200gbps-atlas> python .\servicex\servicex_materialize_branches.py
WARNING:root:Fetched the default calibration configuration for a query. It should have been intentionally configured - using configuration for data format PHYS
Traceback (most recent call last):
  File "C:\Users\gordo\Code\iris-hep\idap-200gbps-atlas\servicex\servicex_materialize_branches.py", line 62, in <module>
    main()
  File "C:\Users\gordo\Code\iris-hep\idap-200gbps-atlas\servicex\servicex_materialize_branches.py", line 56, in main
    files = query_servicex()
  File "C:\Users\gordo\Code\iris-hep\idap-200gbps-atlas\servicex\servicex_materialize_branches.py", line 34, in query_servicex
    ).Select(
  File "C:\Users\gordo\Code\iris-hep\idap-200gbps-atlas\.venv\lib\site-packages\func_adl\object_stream.py", line 150, in Select
    self, _local_simplification(parse_as_ast(f, "Select"))
  File "C:\Users\gordo\Code\iris-hep\idap-200gbps-atlas\.venv\lib\site-packages\func_adl\util_ast.py", line 699, in parse_as_ast
    src_ast = _parse_source_for_lambda(ast_source, caller_name)
  File "C:\Users\gordo\Code\iris-hep\idap-200gbps-atlas\.venv\lib\site-packages\func_adl\util_ast.py", line 620, in _parse_source_for_lambda
    lda, saw_new_line = _get_lambda_in_stream(t_stream, start_token)
  File "C:\Users\gordo\Code\iris-hep\idap-200gbps-atlas\.venv\lib\site-packages\func_adl\util_ast.py", line 564, in _get_lambda_in_stream
    function_source = "(" + tokenize.untokenize(accumulated_tokens).lstrip() + ")"
  File "C:\Users\gordo\AppData\Local\Programs\Python\Python310\lib\tokenize.py", line 280, in untokenize
    out = ut.untokenize(iterable)
  File "C:\Users\gordo\AppData\Local\Programs\Python\Python310\lib\tokenize.py", line 203, in untokenize
    indents.pop()
IndexError: pop from empty list
```

**Comment by gordonwatts** [comment]
Wow - this is an old error - totally missed it. Fixed in #196
